services:
  - type: web
    name: orangecreek-website
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
