databases:
  - name: orangecreek-db
    databaseName: orangecreek
    user: orangecreek
    plan: basic-256mb
    region: frankfurt
    postgresMajorVersion: "16"
    ipAllowList: []

services:
  - type: web
    name: orangecreek-website
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    preDeployCommand: npm run migrate
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SERVER_URL
        value: https://orangecreek.co
      - key: DATABASE_URI
        fromDatabase:
          name: orangecreek-db
          property: connectionString
      - key: PAYLOAD_SECRET
        generateValue: true
